paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - missing input "app-id" which is required by action "actions/create-github-app-token@
      - input "client-id" is not defined in action "actions/create-github-app-token@
