repos:

  - repo: local
    hooks:

      - id: eslint
        name: Run eslint including stylistic
        entry: npx eslint --no-warn-ignored --max-warnings=0
        language: system
        always_run: true
        pass_filenames: false

      - id: prepare-chrome check
        name: Check prepare-chrome script works
        entry: bash -c "./bin/prepare-chrome.sh 0.0.0"
        language: system
        pass_filenames: false

      - id: web-ext lint
        name: web-ext lint
        entry: bash -c "./bin/prepare-firefox.sh 0.0.0 && npx web-ext lint --source-dir dist-firefox/"
        language: system
        pass_filenames: false

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.11.1
    hooks:
      - id: editorconfig-checker
        exclude: \.fodg$
