name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release
        required: true
        type: string


env:
  TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}


jobs:

  release-firefox-extension:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ env.TAG }}
          fetch-depth: "0"

      - uses: actions/setup-node@v7
      - run: |
          npm install
          ./bin/prepare-firefox.sh ${{ github.ref_name }}
      - run: |
          npx web-ext sign --channel listed --source-dir dist-firefox --artifacts-dir .
          files=(*.xpi)
          file=${files[0]}
          mv "$file" "${file%.xpi}-firefox.xpi"
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}

      - uses: actions/upload-artifact@v7
        with:
          name: firefox
          path: "*.xpi"
          if-no-files-found: error


  release-chrome-extension:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ env.TAG }}
          fetch-depth: "0"

      - uses: actions/setup-node@v7
      - run: |
          npm install
          ./bin/prepare-chrome.sh ${{ github.ref_name }}
      - run: echo "CHROME_EXTENSION_ID=$(cat CHROME_EXTENSION_ID)" >> "${GITHUB_ENV}"
      - uses: mnao305/chrome-extension-upload@v6.0.0
        with:
          file-path: "*-chrome.zip"
          glob: true
          extension-id: ${{ env.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}

      - uses: actions/upload-artifact@v7
        with:
          name: chrome
          path: "*.zip"
          if-no-files-found: error


  create-github-release:
    runs-on: ubuntu-latest
    needs:
      - release-firefox-extension
      - release-chrome-extension

    steps:
      - uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ env.TAG }}
          fetch-depth: "0"

      - uses: actions/download-artifact@v8

      - run: |
          gh release create "$TAG" chrome/*.zip firefox/*.xpi
        env:
          GH_TOKEN: ${{ github.token }}
