name: Release Firefox Extension
on:
  workflow_dispatch:

jobs:
  release-firefox-extension:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v7
      - run: |
          npm install
          ./bin/prepare-firefox.sh ${{ github.ref_name }}
      - run: |
          npx web-ext sign --channel listed --source-dir dist-firefox --artifacts-dir .
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
